/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.example.controller;

import java.io.Serializable;

public class Booking implements Serializable {
  private static final long serialVersionUID = 8706333693961181699L;



  /** First Name of Visitor */
  private String first_name;
  /** Last Name of Visitor */
  private String last_name;
  /** Booking Id of the Visitor */
  private String booking_id;
  /** payment type of booking */
  private String payment_type;
  /** Booking source of the Visitor */
  private String booking_source;
  /** Booking Id of the Visitor */
  private String booking_status;

  public Booking(String first_name, String last_name, String booking_id, String payment_type, String booking_source, String booking_status) {
    this.first_name = first_name;
    this.last_name = last_name;
    this.booking_id = booking_id;
    this.payment_type = payment_type;
    this.booking_source = booking_source;
    this.booking_status = booking_status;
  }

  public String getFirst_name() {
    return first_name;
  }

  public String getLast_name() {
    return last_name;
  }

  public void setLast_name(String last_name) {
    this.last_name = last_name;
  }

  public String getBooking_id() {
    return booking_id;
  }

  public void setBooking_id(String booking_id) {
    this.booking_id = booking_id;
  }

  public String getPayment_type() {
    return payment_type;
  }

  public void setPayment_type(String payment_type) {
    this.payment_type = payment_type;
  }

  public String getBooking_source() {
    return booking_source;
  }

  public void setBooking_source(String booking_source) {
    this.booking_source = booking_source;
  }

  public String getBooking_status() {
    return booking_status;
  }

  public void setBooking_status(String booking_status) {
    this.booking_status = booking_status;
  }

  public void setFirst_name(String first_name) {
    this.first_name = first_name;
  }


}










