FROM openjdk:8-jdk-alpine
MAINTAINER Sandysharma@gmail.com
COPY target/data-mesh-visitors-0.0.1-SNAPSHOT.jar data-mesh-visitors-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/data-mesh-visitors-0.0.1-SNAPSHOT.jar"]