/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.example.controller;

import java.io.Serializable;

public class Visitor implements Serializable {
  private static final long serialVersionUID = 8706333693961181699L;

  /** First Name of Visitor */
  private String first_name;
  /** Last Name of Visitor */
  private String last_name;
  /** Booking Id of the Visitor */
  private int age;
  private String booking_id;
  /** payment type of booking */
  private String booking_source;
  /** Booking Id of the Visitor */
  private boolean automated_email;

  public Visitor(String first_name, String last_name, int age, String booking_id, String booking_source, boolean automated_email) {
    this.first_name = first_name;
    this.last_name = last_name;
    this.age = age;
    this.booking_id = booking_id;
    this.booking_source = booking_source;
    this.automated_email = automated_email;
  }

  public String getFirst_name() {
    return first_name;
  }

  public void setFirst_name(String first_name) {
    this.first_name = first_name;
  }

  public String getLast_name() {
    return last_name;
  }

  public void setLast_name(String last_name) {
    this.last_name = last_name;
  }

  public int getAge() {
    return age;
  }

  public void setAge(int age) {
    this.age = age;
  }

  public String getBooking_id() {
    return booking_id;
  }

  public void setBooking_id(String booking_id) {
    this.booking_id = booking_id;
  }

  public String getBooking_source() {
    return booking_source;
  }

  public void setBooking_source(String booking_source) {
    this.booking_source = booking_source;
  }

  public boolean getAutomated_email() {
    return automated_email;
  }

  public void setAutomated_email(boolean automated_email) {
    this.automated_email = automated_email;
  }
}










